name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  eslint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
    - name: Check code
      uses: actions/checkout@v2
      
    - name: Install modules
      run: yarn install

    - name: Run Lints
      run: yarn lint